package picturemouse.backend;


/**
 * Some of the code has been generated by StarUML(tm) Java Add-In.
 * This is the component of the system allowing the Administrator to create a
 * new Newsletter and save it in the database for distribution.
 * 
 * @author Niklas Rahmel
 * @version 01/03/2014
 */



public class BEDistributeNewsletter
{
    
	public void doIt(String content)
	{
            /**
             * database storing all the data.
             */
            BEDatabase database = BEDatabase.getInstance();
            
            // Code to get content Admin entered in GUI and subsequently
            // intialise variable.
            
            /**
             * Newsletter object to store the newsletter for modification.
             * 
             */
            BENewsletter newsletter;
            newsletter = database.getNewsletter();
            newsletter.set(content);
            
            // save newsletter in database.
            database.save(newsletter);
            
            
            
            // Newsletter now ready to be displayed in ReadNewsletter.
	}
}
