package picturemouse.backend;

/**
 * Some of the code has been generated by StarUML(tm) Java Add-In.
 * This is the use case to refuse sign on to the user if the credentials
 * entered don't match any account.
 * 
 * @author Niklas Rahmel
 * @version 01/03/2014
 */


public class BERefuseSignOn
{
    
    public static void doIt()
	{   
             BEDatabase database = BEDatabase.getInstance();
             
            // display error in GUI and ask user to retry.
            
            // call to SignOn.ask() ?
	}
}
