package picturemouse.backend;

/**
 * Some of the code has been generated by StarUML(tm) Java Add-In.
 * At this point the user has already chosen a film
 * 
 * @author Oliver Coleshill
 */
public class BEWriteReview
{
    
	public void doIt(short stars, String text, String username, int filmId)
	{
            
            BEDatabase database = BEDatabase.getInstance();
            
            // Generate the reviewId
            int reviewId = database.getReviews().size();
                       
            //Create new review object
            BEReview review = new BEReview();
            
            //Write review
            review.modify(stars, reviewId, text, username, filmId);
            
            database.save(review);
	
	}
}
