/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package picturemouse.frontend;
import java.sql.Time;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import picturemouse.backend.BEDatabase;
import picturemouse.backend.BEModifyFilmDetails;

/**
 *
 * @author John
 */
public class FEBrowseScreenings extends javax.swing.JFrame {
    String[] filmScreeningStrings;
    DefaultListModel listModel;
    public static Time selectedTime;
    public static Date selectedDate;
    public static int selectedScreeningId;
    private BEModifyFilmDetails action = new BEModifyFilmDetails();
    BEDatabase database = BEDatabase.getInstance();
    boolean filmSelected;
    public static String[] splitSelectedFilmScreeningString;
    
    /**
     * Creates new form BrowseScreening.
     */
    public FEBrowseScreenings() {
        initComponents();
        lblWelcome.setText("Hello " + database.lookupAccount(FESignOn.username, false).getFirstName());
        System.out.println("Fills listbox.");
        fillListBox();
    }

    private void fillListBox()
    {
        filmScreeningStrings = action.browseScreenings(FEBrowseFilms.selectedFilmID);
        listModel = new DefaultListModel<>();
        if (filmScreeningStrings.length > 0){
            System.out.println("Screenigs Array Length:" + filmScreeningStrings.length);
            for (String filmScreeningString: filmScreeningStrings){
                String[] splitFilmScreeningString = filmScreeningString.split(", "); //spliting string up
                listModel.addElement(splitFilmScreeningString[0].trim()); //index [1] is the film name
            }
        } else {
            JOptionPane.showMessageDialog(this, "There are currently no reviews assigned to this film. Please create new screenings first.");
        }
        lbxScreenings.setModel(listModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblBrowseScreenings = new javax.swing.JLabel();
        centrePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbxScreenings = new javax.swing.JList();
        bottomPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnAddScreening = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 153));
        setName("signOn"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        topPanel.setBackground(new java.awt.Color(51, 102, 255));
        topPanel.setName("topPanel"); // NOI18N
        topPanel.setPreferredSize(new java.awt.Dimension(421, 60));

        lblWelcome.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Hello (username)!");
        lblWelcome.setAlignmentX(0.5F);

        lblBrowseScreenings.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblBrowseScreenings.setForeground(new java.awt.Color(255, 255, 255));
        lblBrowseScreenings.setText("Please select a screening for this film.");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblBrowseScreenings)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrowseScreenings)
                .addContainerGap())
        );

        getContentPane().add(topPanel);
        topPanel.getAccessibleContext().setAccessibleName("topPanel");

        centrePanel.setBackground(new java.awt.Color(51, 102, 255));

        lbxScreenings.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lbxScreenings.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lbxScreenings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbxScreeningsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbxScreenings);

        javax.swing.GroupLayout centrePanelLayout = new javax.swing.GroupLayout(centrePanel);
        centrePanel.setLayout(centrePanelLayout);
        centrePanelLayout.setHorizontalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centrePanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        centrePanelLayout.setVerticalGroup(
            centrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        getContentPane().add(centrePanel);

        bottomPanel.setBackground(new java.awt.Color(51, 102, 255));
        bottomPanel.setPreferredSize(new java.awt.Dimension(421, 120));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSelect.setBackground(new java.awt.Color(255, 255, 255));
        btnSelect.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnAddScreening.setBackground(new java.awt.Color(255, 255, 255));
        btnAddScreening.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAddScreening.setText("Add Screening");
        btnAddScreening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddScreeningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnAddScreening, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnAddScreening, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(bottomPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FEModifyFilm().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FEModifyScreening().setVisible(true);
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnAddScreeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddScreeningActionPerformed
        // TODO add your handling code here:
        System.out.println("Adding Screening");
        int result = JOptionPane.showConfirmDialog(this, "Are you sure that "
                + "you want to add a default screening to this film?", "Add Screening Confirmation", 
                JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION)
        {
            action.addScreening(FEBrowseFilms.selectedFilmID);
            fillListBox();
            JOptionPane.showMessageDialog(this, "Screening has been added.");
        }
        
    }//GEN-LAST:event_btnAddScreeningActionPerformed

    private void lbxScreeningsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbxScreeningsValueChanged
        // TODO add your handling code here:
        // Setting Flag
        filmSelected = true;
        
        //Finding the ID of the screening selected using the index of the selected
        //element in the JList
        int selectedJListIndex = this.lbxScreenings.getSelectedIndex();
        String filmScreeningString = filmScreeningStrings[selectedJListIndex]; //Finding string
        String[] splitFilmScreeningString = filmScreeningString.split(", ");
        splitSelectedFilmScreeningString = splitFilmScreeningString; //Saving split string
        
        //Saving attributes as static variables
        String[] timeStrings = splitFilmScreeningString[2].trim().split(":");
        int hour = Integer.valueOf(timeStrings[0]);
        int min = Integer.valueOf(timeStrings[1]);
        int sec = Integer.valueOf(timeStrings[2]);
        
        String[] dateStrings = splitFilmScreeningString[1].trim().split("-");
        int year = Integer.valueOf(dateStrings[0]);
        int month = Integer.valueOf(dateStrings[1]);
        int day = Integer.valueOf(dateStrings[2]);
        selectedTime = new Time(hour, min, sec);
        selectedDate = new Date(year, month, day);
        selectedScreeningId = Integer.valueOf(splitFilmScreeningString[0]);
    }//GEN-LAST:event_lbxScreeningsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEBrowseScreenings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEBrowseScreenings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEBrowseScreenings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEBrowseScreenings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEBrowseScreenings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnAddScreening;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelect;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrowseScreenings;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JList lbxScreenings;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
