package picturemouse;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//

import java.util.ArrayList;


public class Account
{
	private String username;
	private String password;
	private Boolean isAdmin;
	private ArrayList<CinemaTicket> ticketsPurchased;
	private String firstName;
        private boolean SignedOn;
        
        public Account(String username, String password, Boolean isAdmin, ArrayList<CinemaTicket> ticketsPurchased, String firstName) 
        {
            this.username = username;
            this.password = password;
            this.isAdmin = isAdmin;
            this.ticketsPurchased = ticketsPurchased;
            this.firstName = firstName;
            this.SignedOn = false;
        }
        
	public void modify(String username, String password, Boolean isAdmin, ArrayList<CinemaTicket> ticketsPurchased, String firstName)
	{
            this.username = username;
            this.password = password;
            this.isAdmin = isAdmin;
            this.ticketsPurchased = ticketsPurchased;
            this.firstName = firstName;
	}
        
        public String getUsername() {
            return username;
        }
        
        public String getPassword() {
            return password;
        }
        
        public void addTicket(CinemaTicket ticket) {
            ticketsPurchased.add(ticket);
        }
        
        public void signOn(){
            SignedOn = true;
        }
        
        public void signOff(){
            SignedOn = false;
        }
}
