package picturemouse;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class Account
{
	private String username;
	private String password;
	private Boolean isAdmin;
	private ArrayList<CinemaTicket> ticketsPurchased;
	private String firstName;
        
        public Account(String username, String password, Boolean isAdmin, ArrayList<CinemaTicket> ticketsPurchased, String firstName) {
            this.username = username;
            this.password = password;
            this.isAdmin = isAdmin;
            this.ticketsPurchased = ticketsPurchased;
            this.firstName = firstName;
        }
        
	public void modify(Object username, Object password, Object isAdmin, Object ticketsPurchased, Object firstName)
	{
	
	}
        
        
}
