package picturemouse;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookTicket.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//

public class BookTicket
{
	public void doIt(int screening, int seat, Account account)
	{
            CinemaTicket ticket = new CinemaTicket(seat, screening);
            //If the seat in screening is availible then book
            if(screening.available(ticket.getSeatNumber())) {
                account.addTicket(ticket);
                screening.book(ticket.getSeatNumber(), account.getUsername());
            }
	}
}
