package picturemouse;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BrowseFilms.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//

import java.util.ArrayList;


public class BrowseFilms
{
    public String doIt()
    {
        //Finding the database, account, film and screening
        Database database = Database.getInstance();
        ArrayList<Film> films = database.getFilms();
        return "";
    }
}
