package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CinemaTicket.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class CinemaTicket
{
	private int seat;
	private int screeningId;
        
        public CinemaTicket(int seat, int screeningId) {
            this.seat = seat;
            this.screeningId = screeningId;
        }
        
	public void print()
	{
	
	}
	
        public int getSeatNumber(){
            return seat;
        }
}
