package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreateAccount.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class CreateAccount
{
	public void doIt()
	{
	
	}
}
