package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreateAccount.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//

import java.util.ArrayList;


public class CreateAccount
{
	public void doIt(String username, String password, boolean isAdmin, ArrayList<CinemaTicket> ticketsPurchased, String firstName)
	{
            Account newAccount = new Account(username, password, isAdmin, ticketsPurchased, firstName);
            //This database will be replaced by the real database for the system
            Database database = Database.getInstance();
            //Checking if the username already exists
            if(database.lookupAccount(username)==null){
                database.save(newAccount);
            }
	}
}
