package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreateAccount.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//

import java.util.ArrayList;


public class CreateAccount
{
	public void doIt(String username, String password, boolean isAdmin, String firstName)
	{
            //Creating Account with new ArrayList for ticketsPuchased as they would have no tickets
            Account newAccount = new Account(username, password, isAdmin, new ArrayList<CinemaTicket>(), firstName);
            Database database = Database.getInstance();
            //Checking if the username already exists
            if(database.lookupAccount(username)==null){
                database.save(newAccount);
            }
	}
}
