package picturemouse;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Database.java
//  @ Date : 24/02/2014
//  @ Author : John Every
//
//

public class Database
{
	private List<Film> films;
	private List<Review> reviews;
	private List<Account> accounts;
	public void save(Object o)
	{
	
	}
	
	public Film lookupFilm(int filmId)
	{
	
	}
	
	public Review lookupReview(int reviewId)
	{
	
	}
	
	public Account lookupAccount(String username)
	{
	
	}
	
	public void saveToFile()
	{
            FileOutputStream fileOutput = null;
            ObjectOutputStream objectOutput = null;
       
            try
            {
                fileOutput = new FileOutputStream( "datebase.ser" );
                objectOutput = new ObjectOutputStream( fileOutput );
                // Saves the films, reviews and accounts objects into a file.
                objectOutput.writeObject( this.films ); 
                objectOutput.writeObject( this.reviews );
                objectOutput.writeObject( this.accounts );
                
                objectOutput.close();
            }
       
            catch( IOException e )
            {
          
            }
        }
	
	
	public void loadFromFile()
	{
            this.reviews = null;
            this.accounts = null;
            this.films = null;
            
            FileInputStream fileInput = null;
            ObjectInputStream objectInput = null;
       
            try
            {
                fileInput = new FileInputStream("database.ser");
                objectInput = new ObjectInputStream( fileInput );
                
                // Loads the contents of the file and saves it into reviews, 
                // accounts and films respectively.
                this.reviews = ( List<Review> ) objectInput.readObject(); 
                this.accounts = ( List<Account> ) objectInput.readObject(); 
                this.films = ( List<Film> ) objectInput.readObject(); 
                
                objectInput.close();
            }
       
            catch( IOException e )
            {

            }
           
            catch( ClassNotFoundException e )
            {
           
            }  
	}
}
