//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DistributeNewsletter.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class DistributeNewsletter
{
	public void doIt(Object Newsletter n)
	{
	
	}
}
