package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DistributeNewsletter.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class DistributeNewsletter
{
        
        Database db;
    
	public void doIt()
	{
            String content;
            
            // Code to get content from GUI
            
            //Create Newsletter
            db.getNewsletter().set(content);
	}
}
