package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModifyFilmDetails.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class ModifyFilmDetails
{
	public void doIt(Film f)
	{
	
	}
}
