package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModifyReview.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class ModifyReview
{
	public void doIt()
	{
            int reviewID;
            Database db;
            Short stars;
            String text;
            int byUserID;
            int filmID;
            
            db.getReviews().get(reviewID).modify(stars, reviewID, text, byUserID, filmID);
	}
}
