package picturemouse;

import java.util.ArrayList;

/**
 * Some of the code has been generated by StarUML(tm) Java Add-In.
 * This class is instantiated by the front-end and the methods within it 
 * will be called by the front-end to output to the user or input information
 * given by the user into the database. Allows administrators to modify 
 * details of customer accounts.
 * 
 * @version 24/02/2014
 * @author John Every
 */
  
public class ModifyCustomerDetails
{
    /**
     * This method changes the values of the attributes for a chosen account 
     * to new values entered by the user. Then it saves the new account 
     * object's state into the database.
     * 
     * @param oldUsername This corresponds to the old value of the username 
     *                    field for the chosen account.
     * @param newUsername New username field.
     * @param newPassword New password field.
     * @param newIsAdmin  New isAdmin field.
     * @param newTicketsPurchased New TicketsPurchased field(elements are 
     *                            inserted, adapted or removed in front-end).
     * @param newFirstName New first name field. 
     * @param newCreditCardNo New credit card number field.
     */
    public void doIt(String oldUsername, String newUsername, 
            String newPassword, boolean newIsAdmin, 
            ArrayList<CinemaTicket> newTicketsPurchased, 
            String newFirstName, long newCreditCardNo)
    {
        Database database = Database.getInstance();
        Account account = database.lookupAccount(oldUsername, true);
        account.modify(newUsername, newPassword, newIsAdmin, 
                           newTicketsPurchased, newFirstName, newCreditCardNo);
        database.save(account);
    }
    
    // various methods to help produce the front-end for this use case will
    // be later defined.
}

