package picturemouse;


  /** Some of the code has been generated by StarUML(tm) Java Add-In.
   * This is for Admins to modify Reviews already written.
   * 
   * @version 01/03/2014
   * @author Niklas Rahmel
   */





public class ModifyReview
{
	public void doIt(int reviewID)
	{
            /**
             * Database object storing all the reviews
             */
            Database db = Database.getInstance();
            
            /* Old contents of review to be given to GUI to be displayed to
            Admin to modify it.
            
            Short starsOld;
            String textOld;
            int byUserIDOld;
            int filmIDOld;
            
            */
            
            // Variables to store modified values from Admin
            Short stars;
            String text;
            int byUserID;
            int filmID;
            
            // Code to get data input by Admin in GUI to initialise variables
            // declared above
            
            /**
             * Save modified review in database.
             * This only works if reviewID == index of reviewID in 'reviews'
             * in Database, otherwise would have to iterate over all reviews
             * to find review with correct ID or save indices of reviewIDs
             * separately.
             */
            db.getReviews().get(reviewID).modify(stars, reviewID, text, byUserID, filmID);
	}
}
