//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModifyCustomerDetails.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class ModifyCustomerDetails
{
	public void doIt()
	{
	
	}
}
