package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PictureMouse
//  @ File Name : Newsletter.java
//  @ Date : 24/02/2014
//  @ Author : Niklas Rahmel
//
//




public class Newsletter
{
	private String content;
        
	public void set(String content)
	{
            this.content = content;
	}
	
	public String display()
	{
            // for readNewsletter to be displayed in GUI
            return this.content;
	}
}
