package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Newsletter.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class Newsletter
{
	private String content;
	public void distribute()
	{
	
	}
	
	public void display()
	{
	
	}
}
