

package picturemouse;

/**
 * Default Main App as generated by StarUML
 * @author Niklas Rahmel
 */

public class PictureMouse {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
    }
    
}
