package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PrintTicket.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class PrintTicket
{
	public void doIt(CinemaTicket ticket)
	{
            
            //Connect to database
            
            //Get cinema tickets from account
            
            //Check which haven't already expired
            
            //Give a choice of tickets
            
            //Display ticket contents on screen
            
            //Print tickets
            
	
	}
}
