package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PrintTicket.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class PrintTicket
{
	public void doIt(Object CinemaTicket ticket)
	{
	
	}
}
