package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PrintTicket.java
//  @ Date : 24/02/2014
//  @ Author : 
//

import java.awt.*;
import java.awt.print.*;
import java.io.BufferedReader;
import java.io.StringReader;
import java.io.IOException;

public class PrintTicket implements Printable
{
    Database database = Database.getInstance();
    private String toPrint;
    
    public PrintTicket(String printDataIn)
    {
        this.toPrint = printDataIn;
    }
    
    
    public int print(Graphics g, PageFormat pf, int page) throws PrinterException
        {
            if (page > 0){
                return NO_SUCH_PAGE;
            }

            Graphics2D g2d = (Graphics2D)g;
            
            g2d.translate(pf.getImageableX(), pf.getImageableY());

            BufferedReader br = new BufferedReader(new StringReader(toPrint));

            try{
                String line;
                while ((line = br.readLine()) != null){
                    g2d.drawString(line, 100, 100);
                }
            } catch (IOException e) {
                
            }

            return PAGE_EXISTS;
    }
    
    public void doIt(int seat, int screeningId, int filmId) {

        Film film = database.lookupFilm(filmId, false);
        
        String toPrint = "Picture Mouse Cinema Ticket\n" + film.getFilmName() + "\nYour seat number is: " + seat;
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new PrintTicket(toPrint));
        boolean doPrint = job.printDialog();
        
        if (doPrint){
            try{
                job.print();
            } catch (PrinterException e) {
                
            }
        }
        
    }
        
}