package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PictureMouse
//  @ File Name : ReadNewsletter.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class ReadNewsletter{

        Database database = Database.getInstance();

	public void doIt()
	{            
            String Content = database.getNewsletter().display();
            // code to give content to GUI for display
	}
}
