package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReadNewsletter.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class ReadNewsletter{

        Database db = Database.getInstance();

	public void doIt()
	{
            // where does newsletter come from?!
            
            String Content = db.getNewsletter().display();
            // code to give content to GUI for display
            
	}
}
