package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReadNewsletter.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class ReadNewsletter
{
	public void doIt(Newsletter n)
	{
	
	}
}
