package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RefuseSignOn.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class RefuseSignOn
{
	/**
     *
     */
    public static void doIt()
	{
            //display error in GUI and ask user to retry.
	}
}
