package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Review.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class Review
{
	private short stars;
	private int reviewId;
	private String text;
	private String username;
	private int filmId;
        
        
	public void modify(short stars, int reviewId, String text, String username, int filmId)
	{
            this.stars = stars;
            this.reviewId = reviewId;
            this.text = text;
            this.username = username;
            this.filmId = filmId;
	}
        
        public int getReviewId()
        {
            return this.reviewId;
        }
}
