package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Review.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class Review
{
	private short stars;
	private int reviewID;
	private String text;
	private int userID;
	private int film;
        
        
	public void modify(short stars, int reviewID, String text, int byUserID, int filmID)
	{
            this.stars = stars;
            this.reviewID = reviewID;
            this.text = text;
            this.userID = byUserID;
            this.film = filmID;
	}
}
