//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Review.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class Review
{
	private short stars;
	private int reviewId;
	private String text;
	private Account user;
	private Film film;
	public void modify(Object stars, Object reviewId, Object text, Object user, Object film)
	{
	
	}
}
