package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PictureMouse
//  @ File Name : SignOn.java
//  @ Date : 24/02/2014
//  @ Author : Oliver Coleshill
//
//

/**
 * This class will interact with the front end to allow
 * the user to sign in. The front end will run a loop until
 * doIt returns true (indicating that the login has been
 * successful).
 * 
 * @author Oliver Coleshill
 */
public class SignOn
{
    

    Database database = Database.getInstance();
    
    /**
     * Check whether the account is signed on
     * If yes, return true
     * If not, return false so the front end loop can ask again
     */
    public boolean doIt(String u, String p)
	{
            
            //Check signed in
            Account account = database.lookupAccount(u, false);
            
            if (!account.checkSignedOn()){
                
                if (p.equals(account.getPassword())){
                    account.signOn();
                }
                
                return false;
            }
            
            //This means they are signed in, so return true
            else {
                return true;
            }
            	
	}
}
