package picturemouse;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SignOn.java
//  @ Date : 24/02/2014
//  @ Author : Oliver Coleshill
//
//

/**
 *
 * @author Oliver Coleshill
 */
public class SignOn
{
    

        Database database = Database.getInstance();
        
        String u = "";
        String p = "";
    
	public void doIt()
	{
            
            //Check signed in
            Account account = database.lookupAccount(u, false);
            if (account.checkSignedOn() != true){
                ask(u, p);
            }
            	
	}
        
        public void ask(String u, String p){
            
            //Check username exists in the database
            Account account = database.lookupAccount(u, false);
            
            //Check password matches password in Account object
            if (p.equals(account.getPassword()))
            {
                account.signOn();
            } 
            else 
            {
                
            //Else RefuseSignOn
            RefuseSignOn.doIt();
            }
        }
}
