//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WriteReview.java
//  @ Date : 24/02/2014
//  @ Author : 
//
//




public class WriteReview
{
	public void doIt(Object Review r)
	{
	
	}
}
