package picturemouse;

/**
 * Some of the code has been generated by StarUML(tm) Java Add-In.
 * At this point the user has already chosen a film
 * 
 * @author Oliver Coleshill
 */
public class WriteReview
{
    
<<<<<<< HEAD
        Database db = Database.getInstance();
    
	public void doIt(short stars, String text, String username, int filmId)
	{
            // generate this ourselves.
            int reviewID = db.getReviews().size();
=======
	public void doIt(short stars, String text, String username, int filmId)
	{
            
            Database database = Database.getInstance();
            
            // Generate the reviewId
            int reviewId = database.getReviews().size();
>>>>>>> 384886c88c989c0b2874d29c0b4e87a3c8bf5766
                       
            //Create new review object
            Review review = new Review();
            
            //Write review
<<<<<<< HEAD
            review.modify(stars, reviewID, text, username, filmId);
=======
            review.modify(stars, reviewId, text, username, filmId);
>>>>>>> 384886c88c989c0b2874d29c0b4e87a3c8bf5766
            
            database.save(review);
	
	}
}
